FROM docker.litellm.ai/berriai/litellm:main-v1.72.6-stable@sha256:2c3f50ed1ea59ec9e175711c808c3bf15f023643fe50fb1ba1d0f9dc827a356d

RUN apk add --no-cache curl

COPY litellm_config.yaml /app/config.yaml
