import { useCallback, useEffect, useState } from 'react'
import { PdfPageCanvas, useTemplatePdfDocument } from './PdfDocumentCanvas'

/** Display the generated bytes without requiring a browser PDF plug-in. Remount for each output. */
export default function GeneratedPdfPreview({ source, title }) {
  const { document, pages, error } = useTemplatePdfDocument(source)
  const [pageNumber, setPageNumber] = useState(1)
  const [zoomMode, setZoomMode] = useState('fit')
  const [container, setContainer] = useState(null)
  const [width, setWidth] = useState(600)
  const [viewport, setViewport] = useState(null)
  const [renderError, setRenderError] = useState('')
  const onError = useCallback(() => setRenderError('This page could not be displayed. Download the preview to inspect it before continuing.'), [])
  const onViewport = useCallback((value) => setViewport(value), [])

  useEffect(() => {
    if (!container || typeof ResizeObserver === 'undefined') return undefined
    const observer = new ResizeObserver(([entry]) => setWidth(Math.max(160, entry.contentRect.width - 32)))
    observer.observe(container)
    return () => observer.disconnect()
  }, [container])

  const page = pages[pageNumber - 1]
  const rotated = page && Math.abs(page.rotation % 180) === 90
  const pageWidth = page ? (rotated ? page.height : page.width) : 612
  const pageHeight = page ? (rotated ? page.width : page.height) : 792
  const zoom = zoomMode === 'fit' ? Math.min(1.5, width / pageWidth) : Number(zoomMode)
  const changePage = (number) => {
    setViewport(null)
    setRenderError('')
    setPageNumber(number)
    container?.scrollTo?.({ top: 0, left: 0 })
  }

  return (
    <section aria-label={`Preview of ${title}`} className="overflow-hidden rounded border border-brand-line">
      <div className="flex flex-wrap items-center gap-2 border-b border-brand-line bg-brand-surface-2 p-3 text-xs">
        <button type="button" disabled={!page || pageNumber === 1} onClick={() => changePage(pageNumber - 1)} className="rounded border border-brand-line px-3 py-2 disabled:opacity-40">Previous page</button>
        <label className="flex items-center gap-2">Page
          <select aria-label="Preview page" disabled={!page} value={pageNumber} onChange={(event) => changePage(Number(event.target.value))} className="rounded border border-brand-line bg-brand-surface p-2">
            {pages.map((item) => <option key={item.page} value={item.page}>{item.page}</option>)}
          </select>
          <span>of {pages.length || '—'}</span>
        </label>
        <button type="button" disabled={!page || pageNumber === pages.length} onClick={() => changePage(pageNumber + 1)} className="rounded border border-brand-line px-3 py-2 disabled:opacity-40">Next page</button>
        <label className="ml-auto flex items-center gap-2">Zoom
          <select aria-label="Preview zoom" value={zoomMode} onChange={(event) => setZoomMode(event.target.value)} className="rounded border border-brand-line bg-brand-surface p-2">
            <option value="fit">Fit width</option><option value="0.75">75%</option><option value="1">100%</option><option value="1.25">125%</option><option value="1.5">150%</option>
          </select>
        </label>
      </div>
      <div ref={setContainer} className="max-h-[65vh] min-h-64 overflow-auto bg-brand-surface-2 p-4" aria-busy={!error && !renderError && !viewport}>
        {(error || renderError) ? <p role="alert" className="p-4 text-brand-danger">{renderError || 'The PDF preview could not be opened. Download it to inspect every page before continuing.'}</p> : !page ? <p role="status">Opening generated PDF…</p> : (
          <>
            {!viewport && <p role="status">Drawing page {pageNumber}…</p>}
            <div className="relative mx-auto bg-white shadow-sm" style={{ width: pageWidth * zoom, height: pageHeight * zoom }}>
              <PdfPageCanvas document={document} pageNumber={pageNumber} zoom={zoom} onViewport={onViewport} onError={onError} />
            </div>
          </>
        )}
      </div>
      <p className="border-t border-brand-line px-3 py-2 text-xs text-brand-muted">Review every page for correct values, layout and signing locations before publishing or saving.</p>
    </section>
  )
}
