import { useEffect, useState } from 'react'
import { Download, FileSearch, ShieldCheck } from 'lucide-react'
import { createBriefCheck, decideBriefCheckItem, exportBriefCheck, listBriefChecks } from '../api'
import { AlertBanner, WorkspacePage, WorkspacePageHeader } from '../components/ui'
import { useParams } from 'react-router-dom'

const fmt = (value) => value ? new Date(value).toLocaleString() : '—'

function downloadBlob(blob, name) {
  const url = URL.createObjectURL(blob); const link = document.createElement('a')
  link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url)
}

export default function BriefCheckPage() {
  const { matterId } = useParams(); const [items, setItems] = useState([]); const [selected, setSelected] = useState(null)
  const [file, setFile] = useState(null); const [opposingFile, setOpposingFile] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = () => listBriefChecks(matterId).then((data) => { setItems(data.items || []); setSelected((current) => current || data.items?.[0] || null) }).catch(() => setError('Unable to load Brief Check history.'))
  useEffect(() => { load() }, [matterId])
  const run = async (event) => { event.preventDefault(); if (!file) return; setBusy(true); setError(''); try { const result = await createBriefCheck(matterId, { file, opposingFile }); setItems((current) => [result, ...current.filter((item) => item.id !== result.id)]); setSelected(result); setFile(null); event.target.reset() } catch (err) { setError(err?.response?.data?.detail || 'Brief Check could not be completed.') } finally { setBusy(false) } }
  const decide = async (item, decision) => { try { const result = await decideBriefCheckItem(matterId, selected.id, { item_id: item.id, decision }); setSelected(result); setItems((current) => current.map((entry) => entry.id === result.id ? result : entry)) } catch { setError('Decision could not be saved.') } }
  const result = selected?.result || {}
  return <WorkspacePage><WorkspacePageHeader title="Brief Check" description="Review-first citation, quotation, and authority quality control. No absence-of-evidence result is a good-law determination." />
    {error && <AlertBanner variant="error">{error}</AlertBanner>}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
      <section className="rounded-xl border border-brand-line bg-white p-5"><div className="flex items-center gap-2 font-semibold"><FileSearch size={18} /> Run a Brief Check</div><p className="mt-2 text-sm text-brand-muted">DOCX/PDF only; processing is bounded to 15 MB and 300 pages.</p><form onSubmit={run} className="mt-4 space-y-3"><input aria-label="Brief file" type="file" accept=".docx,.pdf" required onChange={(event) => setFile(event.target.files?.[0] || null)} className="block w-full text-sm" /><input aria-label="Opposing brief file" type="file" accept=".docx,.pdf" onChange={(event) => setOpposingFile(event.target.files?.[0] || null)} className="block w-full text-sm" /><button disabled={busy} className="rounded-lg bg-brand-ink px-4 py-2 text-sm font-semibold text-white">{busy ? 'Checking…' : 'Run review'}</button></form><div className="mt-6 border-t border-brand-line pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-brand-muted">Previous checks</p>{items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className={`mt-2 block w-full rounded-lg p-3 text-left text-sm ${selected?.id === item.id ? 'bg-brand-bg-soft' : 'hover:bg-brand-bg-soft'}`}><span className="font-medium">{item.input_filename}</span><span className="block text-xs text-brand-muted">{item.status} · {fmt(item.created_at)}</span></button>)}</div></section>
      <section className="rounded-xl border border-brand-line bg-white p-5">{selected ? <><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Review findings</h2><p className="text-xs text-brand-muted">{selected.input_filename} · {selected.input_sha256.slice(0, 16)}… · {fmt(selected.updated_at)}</p></div><div className="flex gap-2"><button onClick={async () => downloadBlob(await exportBriefCheck(matterId, selected.id, 'report'), 'brief-check-review-report.docx')} className="rounded-lg border px-3 py-2 text-sm"><Download size={15} className="mr-1 inline" />Report</button><button onClick={async () => downloadBlob(await exportBriefCheck(matterId, selected.id, 'toa'), 'table-of-authorities-draft.docx')} className="rounded-lg border px-3 py-2 text-sm">TOA</button></div></div><div className="mt-4 rounded-lg bg-amber-50 p-3 text-sm"><ShieldCheck size={16} className="mr-1 inline" /> Attorney review is required. Coverage is bounded and currentness is unknown unless timestamped evidence is available.</div><FindingGroup title="Citations" items={result.citations} onDecision={decide} /><FindingGroup title="Quotations" items={result.quotations} onDecision={decide} /><FindingGroup title="Omitted-authority candidates" items={result.omitted_authority_candidates} onDecision={decide} /></> : <p className="text-sm text-brand-muted">Run a Brief Check to begin.</p>}</section>
    </div></WorkspacePage>
}

function FindingGroup({ title, items = [], onDecision }) { return <div className="mt-6"><h3 className="font-semibold">{title} <span className="text-xs font-normal text-brand-muted">({items.length})</span></h3>{items.length === 0 ? <p className="mt-2 text-sm text-brand-muted">No items detected.</p> : items.map((item) => <div key={item.id} className="mt-2 rounded-lg border border-brand-line p-3"><div className="flex items-start justify-between gap-3"><div className="text-sm"><span className="font-medium">{item.input || item.quoted_text || item.query}</span><p className="mt-1 text-xs text-brand-muted">{item.status} · confidence {item.confidence ?? 0} · source {item.source_identity || 'not resolved'}</p></div><div className="flex gap-1"><button onClick={() => onDecision(item, 'accepted')} className="rounded border px-2 py-1 text-xs">Accept</button><button onClick={() => onDecision(item, 'needs_followup')} className="rounded border px-2 py-1 text-xs">Follow up</button></div></div></div>)}</div> }
