import { useEffect, useRef, useState } from 'react'
import { Archive, Download, FilePlus2, FolderPlus, History, ShieldCheck } from 'lucide-react'
import { useParams } from 'react-router-dom'
import {
  createResearchRecord, createResearchSnapshot, createResearchWorkspace,
  exportResearchSnapshot, listResearchRecords, listResearchSnapshots,
  listResearchWorkspaceHistory, listResearchWorkspaces,
} from '../api'
import { AlertBanner, WorkspacePage, WorkspacePageHeader } from '../components/ui'

const fmt = (value) => value ? new Date(value).toLocaleString() : '—'
const TYPES = ['issue', 'search', 'folder', 'authority', 'highlight', 'annotation', 'exclusion', 'outline', 'memo', 'alert']
const newIdempotencyKey = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`

function download(blob, name) {
  const url = URL.createObjectURL(blob); const link = document.createElement('a')
  link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url)
}

export default function ResearchWorkspacePage() {
  const { matterId } = useParams()
  const [workspaces, setWorkspaces] = useState([]); const [active, setActive] = useState(null)
  const [records, setRecords] = useState([]); const [snapshots, setSnapshots] = useState([]); const [history, setHistory] = useState([])
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [workspaceTitle, setWorkspaceTitle] = useState(''); const [record, setRecord] = useState({ record_type: 'issue', title: '', body: '', evidence_class: 'model', source_url: '', source_version: '', pinpoint: '', quote: '', exclusion_reason: '' })
  const workspaceAttemptKey = useRef(null); const snapshotAttemptKey = useRef(null)

  const loadWorkspace = async (workspace) => {
    setActive(workspace); setError('')
    try {
      const [recordData, snapshotData, historyData] = await Promise.all([listResearchRecords(matterId, workspace.id), listResearchSnapshots(matterId, workspace.id), listResearchWorkspaceHistory(matterId, workspace.id)])
      setRecords(recordData.items || []); setSnapshots(snapshotData.items || []); setHistory(historyData.items || [])
    } catch { setError('This research workspace is unavailable, stale, or your membership was revoked.') }
  }
  const load = async () => {
    try { const data = await listResearchWorkspaces(matterId); setWorkspaces(data.items || []); if (data.items?.[0]) await loadWorkspace(data.items[0]) } catch { setError('Unable to load research workspaces.') }
  }
  useEffect(() => { load() }, [matterId])
  const makeWorkspace = async (event) => { event.preventDefault(); if (!workspaceTitle.trim()) return; setBusy(true); const key = workspaceAttemptKey.current || (workspaceAttemptKey.current = newIdempotencyKey()); try { const created = await createResearchWorkspace(matterId, { title: workspaceTitle }, key); workspaceAttemptKey.current = null; setWorkspaces((items) => [created, ...items]); setWorkspaceTitle(''); await loadWorkspace(created) } catch (err) { setError(err?.response?.data?.detail || 'Workspace could not be created.') } finally { setBusy(false) } }
  const addRecord = async (event) => { event.preventDefault(); if (!active || !record.title.trim()) return; setBusy(true); try { const payload = { ...record, source_url: record.source_url || null, source_version: record.source_version || null, pinpoint: record.pinpoint || null, quote: record.quote || null, exclusion_reason: record.exclusion_reason || null }; const created = await createResearchRecord(matterId, active.id, payload); setRecords((items) => [...items, created]); setRecord({ record_type: 'issue', title: '', body: '', evidence_class: 'model', source_url: '', source_version: '', pinpoint: '', quote: '', exclusion_reason: '' }) } catch (err) { setError(err?.response?.data?.detail || 'Research record could not be saved.') } finally { setBusy(false) } }
  const snapshot = async () => { if (!active) return; setBusy(true); const key = snapshotAttemptKey.current || (snapshotAttemptKey.current = newIdempotencyKey()); try { const created = await createResearchSnapshot(matterId, active.id, {}, key); snapshotAttemptKey.current = null; setSnapshots((items) => [created, ...items]); const trail = await listResearchWorkspaceHistory(matterId, active.id); setHistory(trail.items || []) } catch { setError('Snapshot could not be created.') } finally { setBusy(false) } }
  const canWrite = active && active.role !== 'viewer'
  return <WorkspacePage width="wide"><WorkspacePageHeader title="Research Workspace" description="Shared, matter-scoped research trails with preserved source links and evidence class. Authority currentness, treatment, and citation format still require attorney review." />
    {error && <AlertBanner variant="error">{error}</AlertBanner>}
    <div className="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)_300px]">
      <aside className="rounded-xl border border-brand-line bg-white p-4"><div className="flex items-center gap-2 font-semibold"><FolderPlus size={17} /> Workspaces</div><form onSubmit={makeWorkspace} className="mt-3 space-y-2"><input aria-label="Workspace title" value={workspaceTitle} onChange={(e) => setWorkspaceTitle(e.target.value)} placeholder="Research issue set" className="w-full rounded border border-brand-line px-3 py-2 text-sm" /><button disabled={busy} className="w-full rounded bg-brand-ink px-3 py-2 text-sm font-semibold text-white">Create workspace</button></form><div className="mt-4 space-y-1">{workspaces.length ? workspaces.map((workspace) => <button key={workspace.id} onClick={() => loadWorkspace(workspace)} className={`w-full rounded p-2 text-left text-sm ${active?.id === workspace.id ? 'bg-brand-bg-soft font-semibold' : 'hover:bg-brand-bg-soft'}`}><span className="block truncate">{workspace.title}</span><span className="text-xs font-normal text-brand-muted">{workspace.role} · {fmt(workspace.updated_at)}</span></button>) : <p className="text-sm text-brand-muted">Create a workspace for this matter to begin a shared trail.</p>}</div></aside>
      <main className="space-y-5">{active ? <><section className="rounded-xl border border-brand-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{active.title}</h2><p className="mt-1 text-xs text-brand-muted">Role: {active.role}. `cited` is source-backed; `verify` needs confirmation; `model` is machine synthesis.</p></div><button disabled={!canWrite || busy} onClick={snapshot} className="rounded border px-3 py-2 text-sm"><Archive size={15} className="mr-1 inline" />Freeze snapshot</button></div><div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm"><ShieldCheck size={16} className="mr-1 inline" />No result is a good-law or Bluebook-correct determination. Use the exact linked source and review stored treatment/currentness states.</div></section>
        {canWrite && <section className="rounded-xl border border-brand-line bg-white p-5"><div className="flex items-center gap-2 font-semibold"><FilePlus2 size={17} /> Add research record</div><form onSubmit={addRecord} className="mt-4 grid gap-3 md:grid-cols-2"><select aria-label="Record type" value={record.record_type} onChange={(e) => setRecord((item) => ({ ...item, record_type: e.target.value }))} className="rounded border border-brand-line px-3 py-2 text-sm">{TYPES.map((type) => <option key={type}>{type}</option>)}</select><select aria-label="Evidence class" value={record.evidence_class} onChange={(e) => setRecord((item) => ({ ...item, evidence_class: e.target.value }))} className="rounded border border-brand-line px-3 py-2 text-sm"><option value="cited">cited — source-backed</option><option value="verify">verify — needs confirmation</option><option value="model">model — machine synthesis</option></select><input aria-label="Record title" required value={record.title} onChange={(e) => setRecord((item) => ({ ...item, title: e.target.value }))} placeholder="Issue, authority, search, or memo heading" className="rounded border border-brand-line px-3 py-2 text-sm md:col-span-2" /><input aria-label="Source URL" value={record.source_url} onChange={(e) => setRecord((item) => ({ ...item, source_url: e.target.value }))} placeholder="Exact source URL (required for cited)" className="rounded border border-brand-line px-3 py-2 text-sm" /><input aria-label="Source version" value={record.source_version} onChange={(e) => setRecord((item) => ({ ...item, source_version: e.target.value }))} placeholder="Source version / as-of note" className="rounded border border-brand-line px-3 py-2 text-sm" /><input aria-label="Pinpoint" value={record.pinpoint} onChange={(e) => setRecord((item) => ({ ...item, pinpoint: e.target.value }))} placeholder="Pinpoint" className="rounded border border-brand-line px-3 py-2 text-sm" /><input aria-label="Exclusion reason" value={record.exclusion_reason} onChange={(e) => setRecord((item) => ({ ...item, exclusion_reason: e.target.value }))} placeholder="Exclusion reason (required for exclusion)" className="rounded border border-brand-line px-3 py-2 text-sm" /><textarea aria-label="Research body" value={record.body} onChange={(e) => setRecord((item) => ({ ...item, body: e.target.value }))} placeholder="Annotation, search terms, outline, memo text, or review note" className="min-h-28 rounded border border-brand-line px-3 py-2 text-sm md:col-span-2" /><button disabled={busy} className="rounded bg-brand-ink px-3 py-2 text-sm font-semibold text-white md:col-span-2">Save record</button></form></section>}
        <section className="rounded-xl border border-brand-line bg-white p-5"><h2 className="font-semibold">Research trail</h2>{records.length ? <div className="mt-3 divide-y divide-brand-line">{records.map((item) => <article key={item.id} className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium">{item.title}</h3><span className="rounded bg-brand-bg-soft px-2 py-0.5 text-xs">{item.record_type} · {item.evidence_class}</span></div><p className="mt-1 whitespace-pre-wrap text-sm text-brand-ink-2">{item.body}</p><p className="mt-2 text-xs text-brand-muted">{item.source_url ? <a className="underline" target="_blank" rel="noreferrer" href={item.source_url}>Open exact source</a> : 'No source URL'} · version {item.source_version || 'unavailable'} · as of {fmt(item.source_as_of)} · currentness {item.currentness_state} · treatment {item.treatment_state}{item.pinpoint ? ` · pinpoint ${item.pinpoint}` : ''}</p>{item.exclusion_reason && <p className="mt-1 text-xs text-brand-muted">Excluded: {item.exclusion_reason}</p>}</article>)}</div> : <p className="mt-3 text-sm text-brand-muted">No saved records. Capture an issue, search, authority, annotation, exclusion, outline, or memo item.</p>}</section></> : <section className="rounded-xl border border-brand-line bg-white p-6 text-sm text-brand-muted">Select or create a workspace.</section>}</main>
      <aside className="space-y-5"> <section className="rounded-xl border border-brand-line bg-white p-4"><div className="flex items-center gap-2 font-semibold"><Archive size={17} /> Immutable snapshots</div>{snapshots.length ? <div className="mt-3 space-y-2">{snapshots.map((item) => <div key={item.id} className="rounded border border-brand-line p-2 text-xs"><p>#{item.sequence} · {item.sha256.slice(0, 12)}…</p><p className="text-brand-muted">{fmt(item.created_at)}</p><button onClick={async () => download(await exportResearchSnapshot(matterId, active.id, item.id), `research-snapshot-${item.sequence}.json`)} className="mt-1 underline"><Download size={12} className="mr-1 inline" />Export review package</button></div>)}</div> : <p className="mt-3 text-sm text-brand-muted">No snapshots yet.</p>}</section><section className="rounded-xl border border-brand-line bg-white p-4"><div className="flex items-center gap-2 font-semibold"><History size={17} /> Activity</div>{history.length ? <ol className="mt-3 space-y-2 text-xs">{history.slice(0, 12).map((item) => <li key={item.id}><span className="font-medium">{item.action.replaceAll('_', ' ')}</span><span className="block text-brand-muted">{fmt(item.created_at)}</span></li>)}</ol> : <p className="mt-3 text-sm text-brand-muted">Activity appears after the first saved action.</p>}</section></aside>
    </div></WorkspacePage>
}
