"""Fictional, common-practice scenarios for the LawHand sales demo.

Each record creates one structured source document and one matter.  The facts,
people, companies, dates, and amounts are invented and deliberately include
questions that make a short product demo feel like real attorney work.
"""

ADDITIONAL_SCENARIOS = [
    {
        "external_key": "demo-sunbeam-drone-demand",
        "primary_plugin": "litigation-legal",
        "matter_type": "litigation",
        "name": "Sunbeam Drone - Rooftop Delivery Demand",
        "practice_area": "Litigation / Commercial Dispute",
        "jurisdiction": "Illinois",
        "status": "Open - Pre-Suit",
        "client": "Sunbeam Drone Delivery, Inc. (fictional)",
        "filename": "07-sunbeam-rooftop-delivery-demand-response.docx",
        "title": "Demand Response and Preservation Plan",
        "subtitle": "Sunbeam Drone Delivery, Inc. - Rooftop Delivery Dispute",
        "lead": "A fictional rooftop delivery pilot ended with a damaged greenhouse, a viral video, and a demand letter that arrives before the insurer has finished its factual review.",
        "facts": [
            "On August 14, a pilot drone landed on the wrong roof after a GPS confidence score fell below the operator's internal threshold. The drone clipped a greenhouse panel and scattered potting soil over an adjoining patio. No person was injured.",
            "The building owner demands $185,000, alleges that a sales representative promised fully autonomous flight, and asks for preservation of flight logs, customer-support messages, the pilot agreement, and marketing videos.",
            "Sunbeam's operations lead says the pilot agreement contains a $25,000 property-damage cap and a 30-day claim notice clause, but the neighborhood marketing reel uses the phrase 'hands-free delivery, every time.'",
        ],
        "issues": [
            "Preservation must cover telemetry, video, dispatch messages, maintenance records, insurance notice, and public posts before routine retention deletes them.",
            "The contract cap, notice clause, and insurance allocation must be compared with the claimant's tort theories and the representative's alleged statement.",
            "The team needs a privileged chronology that separates confirmed facts from the viral video's commentary and identifies who may speak externally.",
        ],
        "decisions": [
            "Decide whether to issue a litigation hold to pilot personnel and the marketing agency today.",
            "Choose a response posture: request supporting invoices, make a nuisance-value offer, or preserve defenses while the carrier investigates.",
            "Approve a temporary pause on rooftop demos and a corrected marketing review until the incident facts are stable.",
        ],
        "suggested_tasks": [
            "Issue legal hold and preserve flight, marketing, and support records",
            "Map contract, insurance, and agency-notice deadlines",
            "Prepare demand-response chronology and settlement authority memo",
        ],
        "demo_prompt": "Build a claim chronology, identify the preservation steps, and draft a measured response that does not concede the disputed marketing statement.",
    },
    {
        "external_key": "demo-pineapple-dsar",
        "primary_plugin": "privacy-legal",
        "matter_type": "privacy",
        "name": "Pineapple Fitness - Member Data Request",
        "practice_area": "Privacy / Data Protection",
        "jurisdiction": "California",
        "status": "Open - Response Window",
        "client": "Pineapple Fitness Studios, LLC (fictional)",
        "filename": "08-pineapple-member-data-request-playbook.docx",
        "title": "Member Data Request Triage File",
        "subtitle": "Pineapple Fitness Studios, LLC - Former Member Request",
        "lead": "A former spin-class regular asks what the studio knows about her while a well-meaning manager has already offered to send a spreadsheet from the front-desk system.",
        "facts": [
            "The requester asks for access, deletion, and a list of disclosures after receiving a promotional text from a nutrition partner. Her account contains class attendance, waiver information, billing history, coaching notes, and a wearable-device integration flag.",
            "The studio uses one booking vendor, one payment processor, and a marketing platform. The front-desk manager exported a member list for the nutrition partner during a spring promotion but does not remember the exact fields included.",
            "A seven-day free trial campaign starts next week, so operations wants a reusable intake and verification process rather than an improvised email exchange.",
        ],
        "issues": [
            "The team must verify the requester without collecting unnecessary new identity data and preserve the request record.",
            "Data maps, vendor terms, retention obligations, and the claimed marketing disclosure need to be reconciled before access or deletion is completed.",
            "Coaching notes may require a separate review for sensitive content, privilege, and information about other members.",
        ],
        "decisions": [
            "Select the identity-verification method and response owner.",
            "Decide whether to pause the nutrition-partner audience until the disclosure history is confirmed.",
            "Approve the member-facing response sequence, including an extension notice if the review cannot finish on time.",
        ],
        "suggested_tasks": [
            "Open verified request record and freeze automatic deletion",
            "Collect booking, payment, and marketing-vendor data maps",
            "Draft access, deletion, and partner-disclosure response package",
        ],
        "demo_prompt": "Create a practical DSAR plan, flag the data that needs human review, and prepare the questions for the booking and marketing vendors.",
    },
    {
        "external_key": "demo-brew-bloom-termination",
        "primary_plugin": "employment-legal",
        "matter_type": "employment",
        "name": "Brew & Bloom - Store Manager Separation",
        "practice_area": "Employment / Workplace Investigation",
        "jurisdiction": "Ohio",
        "status": "Open - Decision Pending",
        "client": "Brew & Bloom Coffee Roasters, Inc. (fictional)",
        "filename": "09-brew-bloom-manager-separation-memo.docx",
        "title": "Store Manager Separation Decision File",
        "subtitle": "Brew & Bloom Coffee Roasters, Inc. - River Market Store",
        "lead": "A popular store manager is accused of changing tip allocations, but the complaint lands two days after she raised scheduling concerns in a staff group chat.",
        "facts": [
            "Three baristas report that the manager manually adjusted pooled tips on four weekend shifts. Payroll records show changes, but the manager says she corrected duplicate clock-ins after a point-of-sale outage.",
            "Two days before the complaint, the manager posted that closing shifts were understaffed and asked whether breaks were being skipped. The regional director replied that the team should discuss concerns privately.",
            "The company has a progressive-discipline policy, a handbook acknowledgment, and short handwritten notes from a supervisor who previously praised the manager's sales results.",
        ],
        "issues": [
            "The tip-allocation evidence, outage history, and witness accounts need a neutral chronology rather than a credibility conclusion based on popularity.",
            "The timing of the scheduling complaint requires a retaliation-sensitive review and consistent treatment comparison.",
            "Final-pay, access revocation, reference language, and communications to a close-knit store team require a coordinated plan.",
        ],
        "decisions": [
            "Decide whether to place the manager on paid leave while the records are preserved.",
            "Approve an interview sequence and identify the decision-maker who was not involved in the scheduling discussion.",
            "Choose between documented coaching, final warning, separation, or further investigation based on the completed record.",
        ],
        "suggested_tasks": [
            "Preserve POS, payroll, schedule, and group-chat records",
            "Prepare witness interview plan and comparator review",
            "Draft separation-or-coaching checklist with final-pay steps",
        ],
        "demo_prompt": "Build an investigation plan that tests the tip allegation and the retaliation risk, then prepare an HR decision checklist.",
    },
    {
        "external_key": "demo-trailtrack-kids-watch",
        "primary_plugin": "product-legal",
        "matter_type": "product",
        "name": "TrailTrack - Kids Adventure Watch Launch",
        "practice_area": "Product / Marketing Review",
        "jurisdiction": "United States",
        "status": "Open - Launch Gate",
        "client": "TrailTrack Outdoor Labs, Inc. (fictional)",
        "filename": "10-trailtrack-kids-watch-launch-review.docx",
        "title": "Kids Adventure Watch Launch Review",
        "subtitle": "TrailTrack Outdoor Labs, Inc. - Beacon Mini Product Launch",
        "lead": "The product team wants a fun September launch for a kids' hiking watch with location sharing, parent challenges, and a battery claim that marketing describes as 'weekend-proof.'",
        "facts": [
            "Beacon Mini records location pings when a parent enables trail mode, shows achievement badges, and lets approved family members see the child's route. The default setup includes a seven-day free premium trial.",
            "Marketing proposes 'Never lose the trail' and 'three-day battery' claims. Internal tests show three days only when location sharing is disabled and notifications are limited.",
            "A retailer requests launch materials, a return policy, and a clear answer on whether family members can download route history after a subscription ends.",
        ],
        "issues": [
            "Product disclosures, age gating, parental controls, and location-sharing defaults must be reconciled before launch copy is approved.",
            "Battery, safety, and durability claims need substantiation and qualified language tied to actual test conditions.",
            "The premium-trial conversion, support scripts, and data-retention explanation need a single customer-facing position.",
        ],
        "decisions": [
            "Approve or revise location-sharing defaults and family-invite controls.",
            "Choose supported battery language and the evidence that must accompany it.",
            "Set the launch gate: legal signoff, support training, retailer FAQ, and incident-escalation owner.",
        ],
        "suggested_tasks": [
            "Review launch claims against test evidence and product behavior",
            "Draft parent-facing location and trial disclosures",
            "Create retailer FAQ and launch-risk signoff checklist",
        ],
        "demo_prompt": "Turn this launch brief into a prioritized product legal checklist, with specific edits to the battery and location-sharing claims.",
    },
    {
        "external_key": "demo-moonbeam-trademark",
        "primary_plugin": "ip-legal",
        "matter_type": "trademark",
        "name": "Moonbeam Bakery - Sparkle Crumb Brand Clash",
        "practice_area": "Intellectual Property / Trademark",
        "jurisdiction": "United States",
        "status": "Open - Brand Decision",
        "client": "Moonbeam Bakery Co. (fictional)",
        "filename": "11-moonbeam-sparkle-crumb-brand-review.docx",
        "title": "Sparkle Crumb Brand Review File",
        "subtitle": "Moonbeam Bakery Co. - New Sprinkle Kit Line",
        "lead": "A neighborhood bakery plans a 'Sparkle Crumb' sprinkle-kit launch, then receives a friendly but firm message from a regional cookie company using a similar name on social media.",
        "facts": [
            "Moonbeam has used 'Sparkle Crumb' on weekend kit labels for six months and plans to expand into online sales, aprons, and video tutorials. Its logo is a crescent moon holding a whisk.",
            "The other company sells packaged cookies under 'Sparkle Crumbs' and points to marketplace listings, a pending application, and customer comments that tag both businesses interchangeably.",
            "Moonbeam's founder wants a practical answer before printing 20,000 new boxes for a holiday pop-up, not a vague warning that every similar name is a lawsuit.",
        ],
        "issues": [
            "The team needs a clearance record that distinguishes word marks, logos, goods, channels, geographic use, and actual confusion evidence.",
            "Packaging, domain, social handle, and tutorial content may create different use and remediation questions.",
            "A response should preserve options without making unsupported admissions about priority or infringement.",
        ],
        "decisions": [
            "Decide whether to pause box printing, use a transitional logo-forward label, or select a new line name.",
            "Approve a targeted clearance search and evidence-preservation plan.",
            "Choose a business-first response proposal, such as channel limits or coexistence discussions.",
        ],
        "suggested_tasks": [
            "Build trademark clearance and usage evidence checklist",
            "Inventory packaging, web, and social uses of the proposed mark",
            "Draft non-admission response and holiday-print decision memo",
        ],
        "demo_prompt": "Create a brand-risk matrix and a practical next-step plan for the founder before the holiday packaging deadline.",
    },
    {
        "external_key": "demo-pearl-pixel-ai-recruiter",
        "primary_plugin": "ai-governance-legal",
        "matter_type": "ai governance",
        "name": "Pearl & Pixel - AI Recruiter Pilot",
        "practice_area": "AI Governance / Vendor Review",
        "jurisdiction": "United States",
        "status": "Open - Pilot Review",
        "client": "Pearl & Pixel Design Studio, LLC (fictional)",
        "filename": "12-pearl-pixel-ai-recruiter-pilot.docx",
        "title": "AI Recruiter Pilot Governance Brief",
        "subtitle": "Pearl & Pixel Design Studio, LLC - Candidate Screening Pilot",
        "lead": "A design studio wants to use an AI tool to sort portfolio submissions before its seasonal hiring sprint, while the vendor promises that its 'bias-free' scoring is ready on day one.",
        "facts": [
            "The tool ranks portfolio text, work samples, and optional video introductions. Recruiters can override the score, but the proposed workflow asks them to review only the top 20 percent of applicants.",
            "The vendor retains prompts and outputs for service improvement unless the customer selects an enterprise setting that is not included in the pilot price.",
            "The studio has fewer than 60 employees, hires remote contractors in several states, and wants a playful candidate experience without pretending that an automated score is a hiring decision.",
        ],
        "issues": [
            "The use case needs an inventory entry, defined business owner, human-review controls, and a clear decision boundary.",
            "Vendor data use, model-change notice, testing evidence, and incident escalation must be captured before candidate materials are uploaded.",
            "Candidate disclosures and recruiter training need to avoid unsupported fairness claims and hidden reliance on a ranking output.",
        ],
        "decisions": [
            "Choose whether the pilot may rank applicants or only summarize portfolios for human review.",
            "Approve minimum vendor commitments for data use, audit information, and change notices.",
            "Set go/no-go criteria, including adverse-impact monitoring and an appeal or alternate-review path.",
        ],
        "suggested_tasks": [
            "Create AI use-case inventory and human-oversight record",
            "Negotiate pilot data-use and model-change controls",
            "Draft candidate notice and recruiter training checklist",
        ],
        "demo_prompt": "Assess this AI hiring pilot, identify the controls needed before launch, and draft a concise go/no-go recommendation.",
    },
    {
        "external_key": "demo-freshnest-supplement-label",
        "primary_plugin": "regulatory-legal",
        "matter_type": "regulatory",
        "name": "FreshNest - Sleepy Tea Label Refresh",
        "practice_area": "Regulatory / Consumer Claims",
        "jurisdiction": "United States",
        "status": "Open - Label Review",
        "client": "FreshNest Pantry Brands, Inc. (fictional)",
        "filename": "13-freshnest-sleepy-tea-label-review.docx",
        "title": "Sleepy Tea Label and Campaign Review",
        "subtitle": "FreshNest Pantry Brands, Inc. - Chamomile Blend Refresh",
        "lead": "A tea company wants to make its calming blend feel more magical for a grocery reset, but the draft label moves from 'bedtime ritual' toward claims that sound like treatment.",
        "facts": [
            "The proposed carton says 'clinically proven to fix restless nights' and the social campaign uses before-and-after sleep-tracker screenshots from employees.",
            "The formula is a familiar herbal blend, the company has taste-test feedback and supplier specifications, but it has not commissioned clinical research on the finished product.",
            "Retail wants final copy in ten days, and the customer-care team asks whether they should remove comments from buyers who say the tea replaced prescribed medication.",
        ],
        "issues": [
            "Product, structure/function, and disease-style language must be separated from unsupported wellness storytelling.",
            "Testimonials, employee screenshots, and influencer briefs need substantiation, disclosure, and moderation guidance.",
            "The company needs a durable approval record so future seasonal campaigns do not reintroduce rejected claims.",
        ],
        "decisions": [
            "Approve compliant claim ranges and the evidence needed for each tier of marketing language.",
            "Decide whether to delay the carton, use a bridge label, or remove the problematic campaign claims.",
            "Set an escalation rule for medication-replacement comments and customer-service scripts.",
        ],
        "suggested_tasks": [
            "Redline label and campaign claims by support level",
            "Create testimonial, influencer, and moderation guidance",
            "Prepare retailer deadline plan and approval archive",
        ],
        "demo_prompt": "Classify the proposed claims, suggest safer alternatives, and build a ten-day approval plan for the label refresh.",
    },
    {
        "external_key": "demo-riverstone-parenting-plan",
        "primary_plugin": "family-law",
        "matter_type": "family",
        "name": "Riverstone - School-Year Parenting Plan",
        "practice_area": "Family Law / Parenting Time",
        "jurisdiction": "Ohio",
        "status": "Open - Mediation Prep",
        "client": "Avery Riverstone (fictional)",
        "filename": "14-riverstone-parenting-plan-prep.docx",
        "title": "School-Year Parenting Plan Preparation",
        "subtitle": "Riverstone Family - Fictional Parenting-Time Mediation",
        "lead": "Two parents agree that their daughter loves robotics club and her rescue rabbit, but they need a workable school-year schedule before a job transfer changes the weekday routine.",
        "facts": [
            "Avery proposes alternating weekends and two weekday dinners. Morgan proposes a 2-2-5-5 schedule, noting that robotics practice is every Tuesday and the child's rabbit stays at Avery's home.",
            "Both parents live within 20 minutes of the school. Morgan may begin a new job with occasional overnight travel, and Avery wants a clear right of first refusal for long work trips.",
            "The parents agree that the child should not carry messages, but they disagree about travel notice, holiday exchanges, school portals, and who pays for tournament fees.",
        ],
        "issues": [
            "The plan needs child-centered transition times, school and activity logistics, and a reliable adjustment process for travel.",
            "Communication boundaries, records access, and expense handling should be specific enough to reduce repeat conflict.",
            "Any support or legal conclusion requires jurisdiction-specific review; the demo focuses on organized facts and negotiation options.",
        ],
        "decisions": [
            "Select a school-week baseline schedule and a backup rule for work travel.",
            "Choose holiday, vacation, and robotics-tournament exchange mechanics.",
            "Approve a mediation agenda and a list of documents each parent should bring.",
        ],
        "suggested_tasks": [
            "Build parenting-time calendar and holiday options",
            "Prepare mediation issue list and communication protocol",
            "Collect school, activity, travel, and expense information",
        ],
        "demo_prompt": "Turn these facts into a neutral mediation agenda and a child-centered parenting-plan checklist without giving jurisdiction-specific legal advice.",
    },
    {
        "external_key": "demo-parkers-festival-citation",
        "primary_plugin": "criminal-defense",
        "matter_type": "criminal defense",
        "name": "Parker - Summer Festival Citation",
        "practice_area": "Criminal Defense / Municipal Case",
        "jurisdiction": "Ohio",
        "status": "Open - Initial Review",
        "client": "Jordan Parker (fictional)",
        "filename": "15-parker-festival-citation-case-notes.docx",
        "title": "Festival Citation Initial Case Notes",
        "subtitle": "Jordan Parker - Fictional Municipal-Court Matter",
        "lead": "A summer festival ends with a citation, a lost phone, and two different accounts of whether a barricade was visible in the crowd.",
        "facts": [
            "Jordan received a municipal citation after stepping into a restricted alley while looking for a friend. The officer's narrative says Jordan ignored two verbal directions; Jordan says music and crowd noise made the directions impossible to hear.",
            "A friend recorded a short video from across the street. The venue may have exterior cameras, and a food-truck owner says staff moved the barricade shortly before the incident.",
            "The first court date is in three weeks. Jordan works in a role that requires occasional background checks and wants to understand the immediate practical steps without posting about the incident online.",
        ],
        "issues": [
            "Video, venue footage, citation language, and witness contact information need timely preservation and an accurate chronology.",
            "Counsel must identify local procedure, possible collateral consequences, and any deadline to request discovery or appear.",
            "The client needs clear communication guidance that protects the defense and avoids amateur social-media investigation.",
        ],
        "decisions": [
            "Decide whether to seek footage immediately and how to document the chain of custody.",
            "Choose the first court-date strategy after reviewing charging language and local procedure.",
            "Approve client instructions for employment questions, online posts, and witness contact.",
        ],
        "suggested_tasks": [
            "Preserve venue, phone, and witness evidence",
            "Create citation timeline and discovery request checklist",
            "Prepare client communication and first-appearance checklist",
        ],
        "demo_prompt": "Build an initial defense-case checklist that prioritizes evidence preservation, court preparation, and client communications.",
    },
    {
        "external_key": "demo-lakeside-bakery-lease",
        "primary_plugin": "real-estate",
        "matter_type": "real estate",
        "name": "Lakeside Bakery - First Brick-and-Mortar Lease",
        "practice_area": "Real Estate / Commercial Lease",
        "jurisdiction": "Michigan",
        "status": "Open - Lease Negotiation",
        "client": "Lakeside Bakery, LLC (fictional)",
        "filename": "16-lakeside-bakery-lease-review.docx",
        "title": "First Store Lease Review Brief",
        "subtitle": "Lakeside Bakery, LLC - Harbor District Retail Space",
        "lead": "A bakery with a devoted pop-up following has found a sunny corner storefront, but the proposed lease makes the tenant responsible for more than flour, frosting, and a cheerful opening day.",
        "facts": [
            "The landlord offers a five-year lease with one option term, percentage rent above a sales threshold, and a broad operating-hours clause tied to the shopping district's calendar.",
            "The space needs a grease interceptor, ventilation work, and a small patio permit. The draft says tenant accepts the premises as-is and is responsible for compliance with all laws affecting its use.",
            "The founder wants a bakery, weekend cake classes, and occasional acoustic music. A competing dessert shop operates two doors away and has an exclusive use provision that has not been provided.",
        ],
        "issues": [
            "Permits, build-out, delivery of utilities, and opening-date contingencies should be allocated before the tenant commits to rent.",
            "Use, exclusivity, assignment, restoration, and percentage-rent terms need to match the actual business plan.",
            "The team needs an organized due-diligence list for zoning, competing restrictions, insurance, and construction bids.",
        ],
        "decisions": [
            "Decide which lease conditions must be satisfied before the personal guaranty is effective.",
            "Approve a proposed permitted-use description that covers classes and music without overpromising.",
            "Choose negotiation positions for tenant improvements, opening rent, and the competing dessert-shop restriction.",
        ],
        "suggested_tasks": [
            "Create lease redline matrix and build-out contingency list",
            "Request exclusivity, zoning, and utility documentation",
            "Prepare opening-date and guaranty negotiation checklist",
        ],
        "demo_prompt": "Review this first-store lease scenario, identify the top negotiation points, and create a practical due-diligence checklist.",
    },
    {
        "external_key": "demo-marigold-estate",
        "primary_plugin": "trust-estate-legal",
        "matter_type": "estate",
        "name": "Marigold Estate - Garden Shop Transition",
        "practice_area": "Trusts & Estates / Probate Planning",
        "jurisdiction": "Ohio",
        "status": "Open - Administration Planning",
        "client": "Marigold Estate Representative (fictional)",
        "filename": "17-marigold-estate-administration-plan.docx",
        "title": "Garden Shop Estate Administration Plan",
        "subtitle": "Estate of Elise Marigold - Fictional Family Business Transition",
        "lead": "A beloved garden-shop owner left a handwritten note, a small greenhouse business, and three adult children who all agree the shop should survive but disagree about who should run it.",
        "facts": [
            "Elise's records include a will from 2014, a later handwritten note naming a daughter to 'keep the shop blooming,' a checking account, greenhouse inventory, a delivery van, and a seasonal lease.",
            "One child works at the shop, one lives out of state, and one believes the business should be sold before spring. Payroll, supplier invoices, and a wedding-flower deposit are due within the month.",
            "The family wants a calm plan for information sharing, immediate business decisions, and a possible memorial scholarship funded by future profits.",
        ],
        "issues": [
            "The will, handwritten note, ownership records, and fiduciary authority require jurisdiction-specific review before anyone distributes assets or acts as owner.",
            "Immediate business continuity, payroll, lease, inventory, and customer deposits must be tracked separately from long-term succession choices.",
            "Beneficiary communication and a transparent asset inventory can reduce conflict while preserving options.",
        ],
        "decisions": [
            "Choose a short-term operations plan and identify who may communicate with vendors.",
            "Approve an estate-information packet and family meeting agenda.",
            "Set decision milestones for sale, continuation, valuation, and any charitable goal.",
        ],
        "suggested_tasks": [
            "Inventory estate and garden-shop records",
            "Create 30-day business-continuity checklist",
            "Prepare beneficiary communication and decision calendar",
        ],
        "demo_prompt": "Organize this estate-and-business transition into immediate, near-term, and long-term decisions while flagging questions for local probate counsel.",
    },
    {
        "external_key": "demo-neighborly-fence-mediation",
        "primary_plugin": "mediation-legal",
        "matter_type": "mediation",
        "name": "Neighborly Fence - Garden and Dog-Run Mediation",
        "practice_area": "Mediation / Property Dispute",
        "jurisdiction": "Ohio",
        "status": "Open - Session Preparation",
        "client": "Neighborly Mediation File (fictional)",
        "filename": "18-neighborly-fence-mediation-brief.docx",
        "title": "Garden Fence Mediation Preparation Brief",
        "subtitle": "Hawthorne and Bell Households - Fictional Neighborhood Dispute",
        "lead": "A charming community garden, an energetic rescue dog, and six inches of fence line have turned two friendly neighbors into people who no longer wave across the driveway.",
        "facts": [
            "The Hawthorne household installed a cedar fence and raised beds after a contractor marked a line using an old landscaping sketch. The Bell household says the fence narrows its planned dog run and blocks access to a shared drainage swale.",
            "Both households have photos, texts, contractor estimates, and different versions of a verbal conversation about where the fence would go. No one wants a lawsuit, but both want the fence issue resolved before winter.",
            "The Bells propose moving one fence segment and sharing drainage costs. The Hawthornes want reimbursement for materials and assurance that the dog run will not damage the garden beds.",
        ],
        "issues": [
            "The mediation needs a neutral inventory of documents, survey questions, costs, and non-monetary interests rather than a conclusion about the legal boundary.",
            "Confidential caucus topics should distinguish settlement flexibility from factual admissions.",
            "A durable agreement may need clear work scope, timing, access rules, releases, and a neighbor-friendly communication plan.",
        ],
        "decisions": [
            "Choose what additional map, survey, or contractor information should be obtained before session.",
            "Set an agenda that begins with shared drainage and pet-safety interests before the reimbursement demand.",
            "Approve settlement ranges and the practical terms that would make a written agreement workable.",
        ],
        "suggested_tasks": [
            "Prepare neutral chronology and document exchange list",
            "Draft mediation agenda, caucus questions, and settlement options",
            "Create written-agreement checklist for work scope and access",
        ],
        "demo_prompt": "Prepare a constructive mediation agenda, identify the information gaps, and outline settlement terms that let both neighbors enjoy their yards again.",
    },
]
