import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
import { dismissReleaseAnnouncement } from './release-announcement.js'

const enabled = process.env.E2E_ONBOARDING_ACCEPTANCE === 'true'
const fixture = name => path.resolve('e2e/fixtures', name)
const messages = () => {
  const file = path.join(process.env.UPLOAD_DIR, 'onboarding-mailbox.jsonl')
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8').trim().split('\n').filter(Boolean).map(JSON.parse) : []
}
const json = async response => { expect(response.ok(), await response.text()).toBeTruthy(); return response.json() }

test('Jane Doe: create matter, review fee, send paperwork, sign, unlock portal, follow up and receive records', async ({ page, browser }) => {
  test.skip(!enabled, 'Requires disposable PostgreSQL onboarding acceptance host')
  test.setTimeout(180_000)
  await page.goto('/login')
  await page.getByRole('button', { name: 'Sign in with email & password' }).click()
  await page.getByLabel('Email', { exact: true }).fill('onboarding@playwright-e2e.example.com')
  await page.getByLabel('Password', { exact: true }).fill(process.env.E2E_USER_PASSWORD || 'Playwright-Only-42!')
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect(page).not.toHaveURL(/\/login$/)
  await page.goto('/matters')
  await dismissReleaseAnnouncement(page)
  await page.getByRole('button', { name: 'New Matter', exact: true }).click()
  await page.getByLabel('Matter Title').fill('Jane Doe divorce acceptance')
  await page.getByRole('button', { name: '+ Create new contact', exact: true }).click()
  await page.getByLabel('First Name', { exact: true }).fill('Jane')
  await page.getByLabel('Last Name', { exact: true }).fill('Doe')
  await page.getByLabel('Email', { exact: true }).fill('jane.onboarding@example.com')
  await page.getByRole('button', { name: 'Create & Select Contact', exact: true }).click()
  await expect(page.getByLabel('Client', { exact: true })).not.toHaveValue('')
  await page.getByRole('button', { name: 'Open Matter', exact: true }).click()
  await expect(page).toHaveURL(/\/matters\/[a-f0-9-]+$/)
  const matterId = new URL(page.url()).pathname.split('/').at(-1)
  const base = `/api/matters/${matterId}`
  expect((await page.request.get(base + '/intake')).status()).toBe(404)
  expect(messages()).toHaveLength(0)
  const upload = async (name, file) => json(await page.request.post(base + '/documents', { multipart: { file: { name, mimeType: 'application/pdf', buffer: fs.readFileSync(fixture(file)) } } }))
  const fee = await upload('Fee agreement.pdf', 'fee-agreement.pdf')
  const form = await upload('General intake form.pdf', 'general-intake.pdf')
  await page.getByRole('button', { name: 'Documents', exact: true }).click()
  await page.getByRole('button', { name: 'Fee agreement.pdf', exact: true }).click()
  await expect(page.getByLabel('PDF page 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close preview', exact: true }).click()
  await page.getByRole('button', { name: 'Client paperwork', exact: true }).click()
  await page.getByLabel('Fee agreement from matter Documents').selectOption(fee.id)
  await expect(page.getByLabel('Client email', { exact: true })).toHaveValue('jane.onboarding@example.com')
  await page.getByLabel('General intake form.pdf', { exact: true }).check()
  await page.getByLabel('Questionnaire — one required question per line').fill('Describe your matter')
  await page.getByLabel('Requested client uploads — one per line').fill('Marriage certificate')
  await page.getByRole('button', { name: 'Send client paperwork', exact: true }).click()
  await expect.poll(() => messages().length).toBe(1)
  const initial = messages()[0]
  expect(initial.body).toContain('General intake form')
  const link = initial.body.match(/https?:[^ ]+token=[A-Za-z0-9_-]+/)[0]
  const clientContext = await browser.newContext({ baseURL: new URL(page.url()).origin })
  const clientPage = await clientContext.newPage()
  try {
    await clientPage.goto(link)
    await expect(clientPage).toHaveURL(/\/portal\/client\/matter$/)
    await expect(clientPage.getByRole('button', { name: 'Messages', exact: true })).toHaveCount(0)
    expect((await clientPage.request.get('/api/portal/client/messages')).status()).toBe(403)
    await clientPage.getByRole('button', { name: 'Review and sign fee agreement', exact: true }).click()
    const requests = await json(await clientPage.request.get('/api/portal/client/signatures'))
    expect(requests).toHaveLength(2)
    const sign = async documentId => {
      const req = requests.find(item => item.document_id === documentId)
      const field = clientPage.locator(`[id="signature-${req.id}"]`)
      const card = field.locator('..')
      await expect(card.getByLabel('PDF page 1', { exact: true })).toBeVisible()
      await field.fill('Jane Doe')
      await card.getByLabel('I have reviewed every page of this document.', { exact: true }).check()
      await card.getByLabel(/I consent to use an electronic signature/).check()
      await card.getByRole('button', { name: 'Sign document', exact: true }).click()
      await expect(field).toHaveCount(0)
    }
    await sign(fee.id)
    await expect.poll(() => messages().length).toBe(2)
    expect(messages()[1].body).toContain('portal')
    const packet = await json(await page.request.get(base + '/intake'))
    expect(packet.requirements.fee_agreement.completed).toBe(true)
    expect(packet.requirements.questionnaire.completed).toBe(false)
    expect(packet.requirements[`document_${form.id.replaceAll('-', '')}`].completed).toBe(false)
    expect(new Date(packet.signing_followup_due_at) - new Date(packet.requirements.fee_agreement.completed_at)).toBe(24 * 60 * 60 * 1000)
    await expect(clientPage.getByRole('button', { name: 'Messages', exact: true })).toBeVisible()
    await sign(form.id)
    await clientPage.getByRole('button', { name: 'Overview', exact: true }).click()
    await clientPage.getByLabel('Describe your matter', { exact: false }).fill('Divorce consultation')
    await clientPage.getByRole('button', { name: 'Submit completed questionnaire' }).click()
    await expect(clientPage.getByText('Questionnaire: Complete', { exact: true })).toBeVisible()
    await clientPage.getByLabel('Upload completed document', { exact: true }).setInputFiles(fixture('general-intake.pdf'))
    await expect(clientPage.getByText('Submitted — awaiting staff review', { exact: true })).toBeVisible()
    const submitted = await json(await page.request.get(base + '/intake'))
    expect(submitted.requirements.upload_1.completed).toBe(false)
    const docId = submitted.requirements.upload_1.submitted_document_id
    await page.reload()
    await page.getByRole('button', { name: 'Client paperwork', exact: true }).click()
    await page.getByText('Review received documents', { exact: true }).click()
    await page.getByLabel('Requirement', { exact: true }).selectOption('upload_1')
    await page.getByLabel('Received document', { exact: true }).selectOption(docId)
    await page.getByLabel('Verification note', { exact: true }).fill('Reviewed the requested record')
    await page.getByRole('button', { name: 'Confirm document is complete', exact: true }).click()
    await expect(page.getByText(/Contact client to schedule by/)).toBeVisible()
    await page.goto('/tasks')
    await expect(page.getByText('Fee agreement signed — follow up with client', { exact: true })).toBeVisible()
    await expect(page.getByText('Intake complete — contact client to schedule initial meeting', { exact: true })).toBeVisible()
  } finally { await clientContext.close() }
})
